v1.2/bloodbank/blood/urls.py
from django.conf.urls import url
from . import views

app_name = 'blood'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    #url(r'^request/$', views.DetailView.as_view(), name='detail'),


    url(r'^signup_donor/$',views.DonorRegister, name='signup_donor'),
    url(r'^signup_hospital/$',views.HospitalRegister, name='signup_hospital'),
    url(r'^request/$', views.BloodRequest, name='request'),

    url(r'^DonorProfile/$', views.ProfileDonor, name='P_donor'),
    url(r'^HospitalProfile/$', views.ProfileHospital, name='P_hospital'),

    url(r'^login/$', views.Login, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),

]

v1.2/bloodbank/bloodbank/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blood/', include('blood.urls')),
]

v1.2/bloodbank/blood/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Blood_request(models.Model):
    name = models.CharField(max_length=250)
    city = models.CharField(max_length=250)
    #state = models.CharField(max_length=250)
    pin_code = models.IntegerField(max_length=10)
    contact1 = models.IntegerField(max_length=10)
    contact2 = models.IntegerField(max_length=10)
    date = models.DateField()
    blood_group = models.CharField(max_length=3)

    def get_absolute_url(self):
        return reverse('blood:index', kwargs={'pk':self.pk})

    def __str__(self):
        return self.name + ' = ' + self.blood_group + ' = ' +self.date.strftime('%Y-%m-%d')

'''
class SignupDonor(models.Model):
    name = models.CharField(max_length=250)
    email = models.CharField(max_length=250)
    #password  = models.CharField(widgets=forms.PasswordInput)
    #repassword  = models.CharField(widgets=forms.PasswordInput)
    city = models.CharField(max_length=250)
    pin_code = models.IntegerField(max_length=10)
    state = models.CharField(max_length=250)
    contact1 = models.IntegerField(max_length=10)
    contact2 = models.IntegerField(max_length=10)
    blood_group = models.CharField(max_length=3)

    def get_absolute_url(self):
        return reverse('blood:index', kwargs={'pk':self.pk})

    def __str__(self):
        return self.name + ' = ' + self.blood_group
'''

v1.2/bloodbank/blood/views.py
from django.views import generic
from .models import Blood_request
from django.contrib.auth import logout
from django.shortcuts import render, redirect
from django.views.generic import View
from .forms import UserForm, RequestForm, HospitalForm, DonorForm, Login
from django.contrib.auth import authenticate, login


class IndexView(generic.ListView):
    template_name = 'blood/fmain.html'
    context_object_name = 'blood_request'

    def get_queryset(self):
        return Blood_request.objects.all()

#class DetailView(generic.DeleteView):
#    model = Blood_request
#    template_name = 'blood/request.html'


class UserFormView(View):
    form_class = UserForm
    template_name = 'blood/signd.html'
    #blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})
    # process form data
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit = False)
            # cleaned (normalized i.e. unifies , formatted)data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user.set_password(password)
            user.save()

            # return user credentials if correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('blood:index')
        return render(request, self.template_name, {'form': form})




#   REQUEST BLOOD

def BloodRequest(request):
    print('!!!!!!!!!!!!!!!!!!!!!!')
    ch=1
    if (ch==2):
        print('nothing is fine')
    #if not request.user.is_authenticated():
    #    print('$$$$$$$$$$$$$$$$$$$$$$$$4')
    #    return render(request, 'blood/fmain.html')
    else:
        print('#############################')
        form = RequestForm(request.POST or None)

        if form.is_valid():
            print('&&&&&&&&&&&&&&&&&&&&&&&&&&7')
            obj = Blood_request()
            obj.name = form.cleaned_data['name']
            obj.city = form.cleaned_data['city']
            obj.pin_code = form.cleaned_data['pin_code']
            obj.contact1 = form.cleaned_data['contact1']
            obj.contact2 = form.cleaned_data['contact2']
            obj.date = form.cleaned_data['date']
            obj.blood_group = form.cleaned_data['blood_group']
            obj.save()
            ch=0
            return redirect('blood:index')

        if ch==1:
            context = {"form" : form,}
            print('here!')
            return render(request, 'blood/request.html',context)


# Hospital Sign Up
def HospitalRegister(request):
    print('inside sign up hospital')
    ch = 1
    if (ch == 2):
        print('nothing is fine')
    #if not request.user.is_authenticated():
    #    print('$$$$$$$$$$$$$$$$$$$$$$$$4')
    #    return render(request, 'blood/fmain.html')
    else:
        print('\n Check1')
        form = HospitalForm(request.POST or None)
        print(form.errors)
        if form.is_valid():
            print('\nCheck2')
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            city = form.cleaned_data['city']
            email = form.cleaned_data['email']
            contact1 = form.cleaned_data['contact1']
            contact2 = form.cleaned_data['contact2']
            pin_code = form.cleaned_data['pin_code']
            state = form.cleaned_data['state']
            user.set_password(password)
            user.save()
            print('\ndeciding point')
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    print('---------NOT IN HERE------------')
                    login(request, user)
                    #requests = Blood_request.objects.filter(user=request.user)
                    return redirect('blood:P_hospital')
        context = {
            "form": form,
        }
        return render(request, 'blood/signh.html', context)






# Donor Sign Up
def DonorRegister(request):
    print('inside sign up donor')
    ch = 1
    if (ch == 2):
        print('nothing is fine')
    #if not request.user.is_authenticated():
    #    print('$$$$$$$$$$$$$$$$$$$$$$$$4')
    #    return render(request, 'blood/fmain.html')
    else:
        print('\n Check1')
        form = DonorForm(request.POST or None)
        print(form.errors)
        if form.is_valid():
            print('\nCheck2')
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            city = form.cleaned_data['city']
            email = form.cleaned_data['email']
            contact1 = form.cleaned_data['contact1']
            contact2 = form.cleaned_data['contact2']
            pin_code = form.cleaned_data['pin_code']
            state = form.cleaned_data['state']
            blood_group = form.cleaned_data['blood_group']
            user.set_password(password)
            user.save()
            print('\ndeciding point')
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    print('---------NOT IN HERE------------')
                    login(request, user)
                    #requests = Blood_request.objects.filter(user=request.user)
                    return redirect('blood:P_donor')
        context = {
            "form": form,
        }
        return render(request, 'blood/signd.html', context)



#Hospital profile page

def ProfileHospital(request):
    return render(request, 'blood/profile_hospital.html')

#Donor profile page

def ProfileDonor(request):
    return render(request, 'blood/profile_donor.html')

#LOGIN page

def Login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'blood/profile_hospital.html')
            else:
                return render(request, 'blood/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'blood/login.html', {'error_message': 'Invalid login'})
    return render(request, 'blood/login.html')




#LOGOUT
def logout_user(request):
    logout(request)
    return redirect('blood:index')


'''
def Login(request):
    form = UserForm(request.GET or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request,'music:P_donor')
    context = {
        "form": form,
    }
    return render(request, 'blood/login.html', context)


    form = (request.POST or None)
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            print('---------NOT IN HERE------------')
            login(request, user)
            # requests = Blood_request.objects.filter(user=request.user)
            return redirect('blood:P_donor')
    else
        return redirect('blood:login')

'''
'''
            user = super(HospitalForm())
            user.username = form.cleaned_data('username')
            user.city = form.cleaned_data('city')
            user.pin_code = form.cleaned_data('pin_code')
            user.contact1 = form.cleaned_data('contact1')
            user.contact2 = form.cleaned_data('contcat2')
            user.email = form.cleaned_data('email')
            user.state = form.cleaned_data('state')

            if commit:
                user.save()
                return user

            return redirect('blood:index')
        else:
            form = UserCreationForm()

        args = {'form' : form,}
        print('now almost there')
        return render(request, 'blood/signh.html',args)

'''

'''
class HospitalFormView(View):
    form_class = UserForm
    template_name = 'blood/signh.html'
    # blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

        # process form data
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)

                    # cleaned (normalized i.e. unifies , formatted)data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user.set_password(password)
            user.save()

                    # return user credentials if correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('blood:index')
        return render(request, self.template_name, {'form': form})

        
        form = PostForm(request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
'''



'''
class SignupDonor(CreateView):
    model = SignupDonor
    fields = ['username','email','password','repassword','city','pin_code','state','contact1','contact2','blood_group']
    template_name = 'blood/signd.html'

    
class BloodRequest(CreateView):
    model = Blood_request

v1.2/bloodbank/blood/templates/blood/fmain.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Blood Book Main</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<script src="https://use.fontawesome.com/09e4a0ac00.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'blood/fmain.css '%}"/>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
{% block content %}
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a href="{% url 'blood:index' %}" class="navbar-brand"><i class="fa fa-tint" aria-hidden="true"></i> Blood Book</a>
			</div>
			<div class="collapse navbar-collapse" id="topNavBar">
				<ul class="nav navbar-nav">
					<li><a href="{% url 'blood:request' %}">Request Blood</a></li>
					<li><a href="#">About</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li><a href="{% url 'blood:signup_donor' %}">
						<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp;
						Sign Up As Donor
						</a>
					</li>
					<li><a href="{% url 'blood:signup_hospital' %}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
						Sign Up As Hospital
						</a>
					</li>

					<li><a href="{% url 'blood:login' %}">
						<span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;
						Login
						</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<div class="container">
		<div class="jumbotron">
			<h2>Search Blood Donors</h2>
			<form class="form-inline search">
  				<div class="form-group">
      				<label>Blood Group</label>
      				<select id="Select" class="form-control">
        				<option>Blood Group</option>
        				<option>A+</option>
        				<option>B+</option>
        				<option>AB+</option>
        				<option>O+</option>
        				<option>A-</option>
        				<option>B-</option>
        				<option>AB-</option>
        				<option>O-</option>
      				</select>
    			</div>
  				<div class="form-group">
    				<label >City</label>
    				<input type="text" class="form-control" id="exampleInputName2" placeholder="City">
  				</div>
  				<button type="submit" class="btn btn-default">Search</button>
			</form>
		</div>
	</div>
	<div class="col-lg-4 col-md-4">
	<div class="thumbnail">
		<h3 class="mid">Blood Requests</h3>
		<table class="table">
			<thead>
				<tr>
					<th>Name</th>
					<th>Blood Group</th>
					<th>Date</th>
				</tr>
			</thead>
			<tbody>




			{% block body %}
				{% for requests in blood_request %}
					<tr>
						<td>{{ requests.name }}</td>
						<td>{{ requests.blood_group }}</td>
						<td>{{ requests.date }}</td>
					</tr>
				{% endfor %}
			{% endblock %}


			<!--
				<tr>
					<td>abc</td>
					<td>A+</td>
					<td>15-09-2017</td>
				</tr>
			-->



			</tbody>
		</table>
	</div>
	</div>
	<div class="col-lg-4 col-md-4">
	<div class="thumbnail">
		<h3 class="mid">Recent Donors</h3>
		<table class="table">
			<thead>
				<tr>
					<th>Name</th>
					<th>Blood Group</th>
					<th>Date</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>bcd</td>
					<td>B+</td>
					<td>09-09-2017</td>
				</tr>
			</tbody>
		</table>
	</div>
	</div>
	<div class="col-lg-4 col-md-4">
	<div class="thumbnail">
		<h3 class="mid">Upcoming Blood Donation Camps</h3>
		<table class="table">
			<thead>
				<tr>
					<th>Hospital</th>
					<th>City</th>
					<th>Date</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>xyz</td>
					<td>Patiala</td>
					<td>20-09-2017</td>
				</tr>
			</tbody>
		</table>
	</div>
	</div>
{% endblock %}
</body>
</html>

v1.2/bloodbank/blood/templates/blood/profile_hospital.html
<!DOCTYPE html>
<html>
<head>
	<title>Hospital Profile</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'blood/p_hospital.css '%}">
	<script src="https://use.fontawesome.com/09e4a0ac00.js"></script>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-nav-demo"  aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a href="#" class="navbar-brand"><i class="fa fa-tint" aria-hidden="true"></i> Blood Book</a>
			</div>
			<div class="collapse navbar-collapse" id="bs-nav-demo">
				<ul class="nav navbar-nav">
					<li><a href="{% url 'blood:request' %}">Blood Requests</a></li>
					<li><a href="#">Update Profile</a></li>
					<li><a href="#">Send Reports</a></li>
					<li><a href="#">Camps</a></li>
					<li><a href="#">About</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li>
						<a href="#">
							<span class="glyphicon glyphicon-send" aria-hidden="true"></span>&nbsp;
							Notifications
						</a>
					</li>
					<li>
						<a href="{% url 'blood:logout' %}">
							<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
							Logout
						</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<div class="jumbotron pp">
	<div class="col-lg-2 col-md-2">
	<div class="thumbnail profile_pic">
		<img class="profile_pic" src="http://st3.cricketcountry.com/wp-content/uploads/cricket/20160617015246.jpeg">
	</div>
	</div>
	<div class="col-lg-4 col-md-4">
	<div class="name">
		<h1>ABC Hospital</h1>
		<h4>Patiala</h4>
		<h4>Punjab</h4>
		<button class="btn btn-default bt">Ask for More Permissions</button>
	</div>
	</div>

	<div class="col-lg-3 col-md-3">
	<div class="pi thumbnail">
		<h2>Number units of Blood Donated</h2>
		<h1>630</h1>
	</div>
	</div>


	<div class="col-lg-3 col-md-3">
	<div class="pi thumbnail">
		<h2>Number of units currently available</h2>
		<h1>40</h1>
	</div>
	</div>
	</div>

	<div class="container">
	<div class="jumbotron units">
		<h2 id="each">Units of each Blood Type</h2>
	<div class="col-lg-3 col-md-3">
	<div class="thumbnail">
		<h2>A+</h2>
		<h1>9</h1>
	</div>
	</div>

	<div class="col-lg-3 col-md-3">
	<div class="thumbnail">
		<h2>B+</h2>
		<h1>11</h1>
	</div>
	</div>

	<div class="col-lg-3 col-md-3">
	<div class="thumbnail">
		<h2>AB+</h2>
		<h1>7</h1>
	</div>
	</div>

	<div class="col-lg-3 col-md-3">
	<div class="thumbnail">
		<h2>O+</h2>
		<h1>8</h1>
	</div>
	</div>

	<div class="col-lg-3 col-md-3">
	<div class="thumbnail">
		<h2>A-</h2>
		<h1>2</h1>
	</div>
	</div>

	<div class="col-lg-3 col-md-3">
	<div class="thumbnail">
		<h2>B-</h2>
		<h1>2</h1>
	</div>
	</div>

	<div class="col-lg-3 col-md-3">
	<div class="thumbnail">
		<h2>AB-</h2>
		<h1>1</h1>
	</div>
	</div>

	<div class="col-lg-3 col-md-3">
	<div class="thumbnail">
		<h2>O-</h2>
		<h1>0</h1>
	</div>
	</div>
	</div>
	</div>
	
	<div class="container">
		<div class="jumbotron org">
			<h2>Organise a Blood Donation Camp</h2>
			<form class="form-inline org">
  				<div class="form-group">
      				<label>Date</label>
      				<input type="Date" class="form-control" id="exampleInputName2">
    			</div>
  				<div class="form-group">
    				<label>City</label>
    				<input type="text" class="form-control"  placeholder="City">
  				</div>
  				<div class="form-group">
    				<label >Place</label>
    				<input type="text" class="form-control" placeholder="Place">
  				</div>
  				<button type="submit" class="btn btn-default">Submit</button>
			</form>
		</div>
	</div>

	<div class="container">
		<div class="jumbotron mid">
		<h2 class="mid">Donors History</h2>
		<table class="table mid">
			<thead>
				<tr>
					<th class="mid">Sno.</th>
					<th class="mid">Donor Name</th>
					<th class="mid">Date</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>1</td>
					<td>pahul</td>
					<td>15-09-2017</td>
				</tr>
			</tbody>
		</table>

		<button class="btn bt">View All</button>
		</div>
	</div>

	<div class="container">
		<div class="jumbotron mid">
		<h2 class="mid">Patient History</h2>
		<table class="table mid">
			<thead>
				<tr>
					<th class="mid">Sno.</th>
					<th class="mid">Patient Name</th>
					<th class="mid">Date</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>1</td>
					<td>naman</td>
					<td>15-09-2017</td>
				</tr>
			</tbody>
		</table>

		<button class="btn bt">View All</button>
		</div>
	</div>
</body>
</html>

v1.2/bloodbank/blood/templates/blood/request1.html
<!DOCTYPE html>
<html lang="en">
<html>
<head>
	<meta charset="UTF-8">
	<title>Request Blood</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'blood/request.css '%}">
</head>
<body>
	<div class="container">
	<div class="row">
	<div class="col-xs-6 col-md-offset-3">

		<form method="post" enctype="multipart/form-data">
			<h1>Blood Book</h1>
			<h3>Request Blood</h3>
			{% csrf_token %}
            <div class="form-group">

                    <label class=""><label for="id_name">Name</label></label>{{ form.blood_group }}
                    <div class=""><input type="text" name="name" maxlength="250" required id="id_name" />{{ form.name }}</div>

                    <div class="form-group">
                        <span class="text-danger small"></span>
                    </div>
                    <label class=""><label for="id_city">City:</label></label>
                    <div class=""><input type="text" name="city" maxlength="250" required id="id_city" />{{ form.city }}</div>

                    <div class="form-group">
                        <span class="text-danger small"></span>
                    </div>
                    <label class=""><label for="id_pin_code">Pin code:</label></label>
                    <div class=""><input type="number" name="pin_code" required id="id_pin_code" />{{ form.pin_code }}</div>

                    <div class="form-group">
                        <span class="text-danger small"></span>
                    </div>
                    <label class=""><label for="id_contact1">Contact1:</label></label>
                    <div class=""><input type="number" name="contact1" required id="id_contact1" />{{ form.contact1 }}</div>

                    <div class="form-group">
                        <span class="text-danger small"></span>
                    </div>
                    <label class=""><label for="id_contact2">Contact2:</label></label>
                    <div class=""><input type="number" name="contact2" required id="id_contact2" />{{ form.contact2 }}</div>

                    <div class="form-group">
                        <span class="text-danger small"></span>
                    </div>
                    <label class=""><label for="id_date">Date:</label></label>
                    <div class=""><input type="text" name="date" required id="id_date" />{{ form.date }}</div>

                    <div class="form-group">
                        <span class="text-danger small"></span>
                    </div>
                    <label class=""><label for="id_blood_group">Blood group:</label></label>
                    <div class=""><input type="text" name="blood_group" maxlength="3" required id="id_blood_group" />{{ form.blood_group }}</div>

                <button type="submit" class="btn btn-default">Post
                </button>

            </div>

		</form>
		</div>
		</div>
	</div>
</body>

v1.2/bloodbank/blood/templates/blood/request2.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" >{{ field.label_tag }}</label>
        <div>
         class="col-sm-10">{{ field }}
        </div>
    </div>
{% endfor %}

v1.2/bloodbank/blood/templates/blood/request_original.html
<!DOCTYPE html>
<html lang="en">
<html>
<head>
	<meta charset="UTF-8">
	<title>Request Blood</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'blood/request.css '%}">
</head>
<body>
	<div class="container">
	<div class="row">
	<div class="col-xs-6 col-md-offset-3">

		<form method="post" enctype="multipart/form-data">
			<h1>Blood Book</h1>
			<h3>Request Blood</h3>
			{% csrf_token %}
            <div class="form-group">

                    <label class=""><label for="id_name">{{ field.name }}</label></label>
                    <div class=""><input type="text" name="name" maxlength="250" required id="id_name" />{{ form.name }}</div>

                    <div class="form-group">
                        <span class="text-danger small"></span>
                    </div>
                    <label class=""><label for="id_city">City:</label></label>
                    <div class=""><input type="text" name="city" maxlength="250" required id="id_city" />{{ form.city }}</div>

                    <div class="form-group">
                        <span class="text-danger small"></span>
                    </div>
                    <label class=""><label for="id_pin_code">Pin code:</label></label>
                    <div class=""><input type="number" name="pin_code" required id="id_pin_code" />{{ form.pin_code }}</div>

                    <div class="form-group">
                        <span class="text-danger small"></span>
                    </div>
                    <label class=""><label for="id_contact1">Contact1:</label></label>
                    <div class=""><input type="number" name="contact1" required id="id_contact1" />{{ form.contact1 }}</div>

                    <div class="form-group">
                        <span class="text-danger small"></span>
                    </div>
                    <label class=""><label for="id_contact2">Contact2:</label></label>
                    <div class=""><input type="number" name="contact2" required id="id_contact2" />{{ form.contact2 }}</div>

                    <div class="form-group">
                        <span class="text-danger small"></span>
                    </div>
                    <label class=""><label for="id_date">Date:</label></label>
                    <div class=""><input type="text" name="date" required id="id_date" />{{ form.date }}</div>

                    <div class="form-group">
                        <span class="text-danger small"></span>
                    </div>
                    <label class=""><label for="id_blood_group">Blood group:</label></label>
                    <div class=""><input type="text" name="blood_group" maxlength="3" required id="id_blood_group" />{{ form.blood_group }}</div>

                <button type="submit" class="btn btn-default">Post
                </button>

            </div>

		</form>
		</div>
		</div>
	</div>
</body>